### ISSUE TITLE
Critical Failure - corrupted translation file

### ISSUE THREAD

**Issue by thihara** [jazzband/django-taggit#742] opened 2021-07-02 16:53 UTC
There's a critical failure in version 1.5.0

A translation file is bad 

`OSError: [Errno 0] Bad magic number: '/usr/local/lib/python3.7/site-packages/taggit/locale/uk/LC_MESSAGES/django.mo'`

Full stacktrace

```
Traceback (most recent call last):
File "./matific/wsgi.py", line 21, in <module>
application = get_wsgi_application()
File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
app_config.ready()
File "/usr/local/lib/python3.7/site-packages/cmsplugin_cascade/apps.py", line 19, in ready
stylesSet = str(settings.CKEDITOR_SETTINGS.get('stylesSet'))
File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 156, in __text_cast
return func(*self.__args, **self.__kw)
File "/usr/local/lib/python3.7/site-packages/django/utils/text.py", line 413, in _format_lazy
return format_string.format(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 156, in __text_cast
return func(*self.__args, **self.__kw)
File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 58, in reverse
app_list = resolver.app_dict[ns]
File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 513, in app_dict
self._populate()
File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 447, in _populate
for url_pattern in reversed(self.url_patterns):
File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
res = instance.__dict__[self.name] = self.func(instance)
File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
res = instance.__dict__[self.name] = self.func(instance)
File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "./matific/urls.py", line 28, in <module>
urlpatterns += l10n_i18n_patterns(url(r'^', include("matific.cms_urls")),)
File "/usr/local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
urlconf_module = import_module(urlconf_module)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "./matific/cms_urls.py", line 19, in <module>
urlpatterns = get_app_patterns()
File "./localization/cms_customize.py", line 107, in get_app_patterns
return _get_app_patterns_for_all_languages(site)
File "./localization/cms_customize.py", line 76, in _get_app_patterns_for_all_languages
with override(lang):
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/__init__.py", line 185, in __enter__
activate(self.language)
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/__init__.py", line 170, in activate
return _trans.activate(language)
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 278, in activate
_active.value = translation(language)
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 267, in translation
_translations[language] = DjangoTranslation(language)
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 154, in __init__
self._add_installed_apps_translations()
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 202, in _add_installed_apps_translations
translation = self._new_gnu_trans(localedir)
File "/usr/local/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 180, in _new_gnu_trans
fallback=use_null_fallback,
File "/usr/local/lib/python3.7/gettext.py", line 533, in translation
t = _translations.setdefault(key, class_(fp))
File "/usr/local/lib/python3.7/gettext.py", line 260, in __init__
self._parse(fp)
File "/usr/local/lib/python3.7/gettext.py", line 361, in _parse
raise OSError(0, 'Bad magic number', filename)
OSError: [Errno 0] Bad magic number: '/usr/local/lib/python3.7/site-packages/taggit/locale/uk/LC_MESSAGES/django.mo'
```

**Comment by thihara** [comment] 2021-07-03 01:28
I fixed the dependency version at 1.4.0 to get around this.

**Comment by tijuca** [comment] 2021-07-03 06:34
I can confirm this problem.

Additional side note, the compiled message catalog for Danish is missing.

**Comment by rtpg** [comment] 2021-07-06 01:45
Going to re-open until we can confirm that the issue is fixed in the latest release. 

@tijuca @thihara would either of you mind trying out the 1.5.1 release to confirm that your issue is fixed there?

**Comment by tijuca** [comment] 2021-07-06 09:39
Thanks, looks good to me.

**Closed** 2021-07-07 00:43 UTC
Labels: bug
