### ISSUE TITLE
Admin widget error in Django 2.1

### ISSUE THREAD

**Issue by ahknight** [jazzband/django-taggit#596] opened 2019-03-02 02:52 UTC
When using the admin widget in Django 2.1 I get the following error:

`'TypeError: render() got an unexpected keyword argument 'renderer'`

By process of elimination, when I remove `tags` from the `fieldset` for my model the admin suddenly works again.

Django 2.1 and django-taggit 0.24.0

```
Traceback (most recent call last):
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 173, in render
    return self._render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/utils/html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/Users/ahknight/.virtualenvs/milton/lib/python3.7/site-packages/Django-2.1.7-py3.7.egg/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
```

**Comment by cberry216** [comment] 2019-03-06 14:13
The same thing is happening to me. The error only occurs when the TaggableManager is added as a field to a model. The error only affects those models that have the TaggableManager and no other models.

**Comment by jdufresne** [comment] 2019-03-07 03:02
I'm unable to reproduce. The `renderer` argument was added in 04c5a3823782b50674e04eee9ea6e63a4078eb0c.

Can you provide a minimal project that demonstrates the issue that I can use to reproduce?

Or, can you tell me how to modify the tests in #597 to trigger the bug?

If so, I can dive deeper to fix it. Thanks!

**Comment by cberry216** [comment] 2019-03-07 11:06
I was able to solve it by using taggit v0.23.0.

**Comment by jdufresne** [comment] 2019-03-07 12:24
@ahknight original report says they are using 0.24.0, so does this still exist?

**Comment by ahknight** [comment] 2019-03-07 13:48
Yes, this was Django 2.1 and taggit 0.24.0. I’ll see if I can whip up a minimum. If not, this is in ahknight/milton.

**Comment by jdufresne** [comment] 2019-03-07 14:16
https://github.com/ahknight/milton gives me a 404. Is it a private repo?

**Comment by ahknight** [comment] 2019-03-07 14:45
Bah, wrong service. Here: https://bitbucket.org/codepoet/milton

**Comment by jdufresne** [comment] 2019-03-08 15:29
Ah, ok. Let me know if you can create a minimal test case with explicit steps to reproduce and I'll take a look. Thanks!

**Comment by dnl-krsvch** [comment] 2019-09-23 13:27
So, The same thing when I added to models TaggableManager it happened. toggit version is 0.22.2

**Comment by jdufresne** [comment] 2019-12-04 01:45
Sounds like this has been been fixed in recent version. Further, Django 2.1 is now EOL. If you can still trigger the error, please provide details.

**Closed by jdufresne** 2019-12-04 01:45 UTC
Labels: needsinfo
